### ISSUE TITLE
When receiving HTTP response, it is showb as a Json decode error

### ISSUE THREAD

**Issue by AndreasBomholtz** [Wappsto/wappsto-python#115]
`Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,729 - DEBUG: Raw Send Json: b'[{"jsonrpc": "2.0", "method": "POST", "params": {"url": "/network", "data": {"name": "Barometer (incl. Temperature & Humidity)", "device": [{"name": "Barometer", "product": "SUITKASE_Barometer", "protocol": "", "serial": "", "manufacturer": "Seluxit", "communication": "", "description": "BMP280 is a high-precision, low-power combined humidity, pressure, and temperature sensor. Accuracy:  \\u00b11.0 pressure & temperature,  \\u00b13 relative humidity.", "version": "2.0", "value": [{"name": "Temperature", "type": "temperature", "permission": "r", "state": [{"data": "0", "type": "Report", "timestamp": "2020-04-01T07:50:13.920622Z", "meta": {"id": "33dcc357-a5b4-4f84-8691-a446c8afefde", "type": "state", "version": "2.0"}}], "number": {"min": -40, "max": 85, "step": 0.5, "unit": "celsius"}, "meta": {"id": "7babce20-da24-46f5-85dd-8c5f3675c46e", "type": "value", "version": "2.0"}}, {"name": "Humidity", "type": "humidity", "permission": "r", "state": [{"data": "0", "type": "Report", "timestamp": "2020-04-01T07:50:13.920622Z", "meta": {"id": "a4b501ca-1e70-44fc-a53a-c104ab27eb9e", "type": "state", "version": "2.0"}}], "number": {"min": 0, "max": 100, "step": 1, "unit": "percentage"}, "meta": {"id": "6786c93f-b92e-4b77-8a6b-e3d6257a6cad", "type": "value", "version": "2.0"}}, {"name": "Pressure", "type": "atmospheric_pressure", "permission": "r", "state": [{"data": "300", "type": "Report", "timestamp": "2020-04-01T07:50:13.920622Z", "meta": {"id": "5e684962-08db-4755-92ff-b3f4b3a5273e", "type": "state", "version": "2.0"}}], "number": {"min": 300, "max": 1100, "step": 1, "unit": "hPa"}, "meta": {"id": "15eebb05-7993-4671-95b4-b5a43675b449", "type": "value", "version": "2.0"}}, {"name": "Sensor update interval", "type": "interval", "permission": "rw", "state": [{"data": "10", "type": "Report", "timestamp": "2020-04-01T07:50:13.920622Z", "meta": {"id": "122859a0-6af1-470d-b62b-1ffb3a3181b3", "type": "state", "version": "2.0"}}, {"data": "10", "type": "Control", "timestamp": "2020-04-01T07:50:13.920622Z", "meta": {"id": "bdd3d4a8-a0e5-4253-868f-0f0f718c6079", "type": "state", "version": "2.0"}}], "number": {"min": 1, "max": 1200, "step": 1, "unit": "second"}, "meta": {"id": "d59d6cb0-5380-4ab0-8e9b-f3c5b3317952", "type": "value", "version": "2.0"}}], "meta": {"id": "b5670ffd-cdae-4cfe-865c-ad8bed3aa1f5", "version": "2.0", "type": "device"}}, {"name": "LED + Button", "product": "SUITKASE_ButtonLED", "manufacturer": "Seluxit", "description": "The Grove - Red LED Button is stable and reliable with 100 000 times long life. With the build-in LED, you can apply it to many interesting projects, it is really useful to use the LED to show the status of the button. We use a high-quality N-Channel MOSFET to control the LED to ensure the high switching speed and low power consumption.", "version": "2.0", "value": [{"name": "Button", "type": "button", "permission": "r", "state": [{"data": "0", "type": "Report", "timestamp": "2020-04-01T07:53:05.085172Z", "meta": {"id": "399ae107-a140-4ddd-9842-05ac93ef4971", "type": "state", "version": "2.0"}}], "number": {"min": 0, "max": 1, "step": 1, "unit": ""}, "meta": {"id": "0e2751d5-c8f3-4e55-92ee-33f40fe8d261", "type": "value", "version": "2.0"}}, {"name": "LED On-off", "type": "led", "permission": "rw", "state": [{"data": "0", "type": "Report", "timestamp": "2020-04-01T07:53:05.085172Z", "meta": {"id": "215a7f3c-79ed-427e-8f99-2b1f26581f30", "type": "state", "version": "2.0"}}, {"data": "0", "type": "Control", "timestamp": "2020-04-01T07:53:05.085172Z", "meta": {"id": "873ecba6-087b-4937-af7d-5d9e8fb7bcbe", "type": "state", "version": "2.0"}}], "number": {"min": 0, "max": 1, "step": 1, "unit": ""}, "meta": {"id": "2d6051ac-0378-4831-808f-d032ec0d8f64", "type": "value", "version": "2.0"}}], "meta": {"id": "1b4689d8-d52e-4932-a016-69ce35dfeeb6", "version": "2.0", "type": "device"}}], "meta": {"id": "7d768190-d86d-467d-9a6c-d8fea126ec56", "version": "2.0", "type": "network", "upgradable": true}}}, "id": 3}]'
Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,738 - DEBUG: The whole network Barometer (incl. Temperature & Humidity) added to Sending queue <wappsto.connection.seluxit_rpc.SeluxitRpc object at 0x762a3ef0>.
Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,787 - ERROR: Json decoding error: [{"jsonrpc":"2.0","id":1,"error":{"code":-32006,"message":"Not Found","data":{"meta":{"type":"httpresponse","version":"2.0"},"message":"Id in url not found","data":{"wrong_parameter":"id","wrong_value":"7d768190-d86d-467d-9a6c-d8fea126ec56"},"code":9900147,"service":"data_collector","internal_code":"id_in_url_not_found","debug":{"file_line":"/usr/src/app/core/middleware/parsers/parser_path/helpers/checkers.rb:36:in `check_id'","backtrace":["/usr/src/app/core/middleware/parsers/parser_path/helpers/checkers.rb:36:in `check_id'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:46:in `block in check_url'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:10:in `each'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:10:in `check_url'","/usr/src/app/core/middleware/parsers/parser_path/parser_path.rb:45:in `parse'","/usr/src/app/core/middleware/parsers/parser_path/parser_path.rb:13:in `call'","/usr/src/app/middleware/convert_old/convert_old.rb:17:in `call'","/usr/src/app/core/middleware/wallet/wallet.rb:20:in `call'","/usr/src/app/core/middleware/session/session.rb:14:in `call'","/usr/src/app/core/middleware/store/store.rb:12:in `call'","/usr/src/app/core/middleware/after_operation/after_operation.rb:8:in `call'","/usr/src/app/core/middleware/documentstore/documentstore.rb:15:in `call'","/usr/src/app/core/middleware/catchers/catch.rb:18:in `block in call'","/usr/src/app/core/middleware/catchers/catch.rb:17:in `catch'","/usr/src/app/core/middleware/catchers/catch.rb:17:in `call'","/usr/src/app/core/middleware/events/events.rb:12:in `call'","/usr/src/app/core/middleware/catchers/rescuer.rb:18:in `call'","/usr/src/app/core/middleware/identifier/trace.rb:17:in `call'","/usr/src/app/core/middleware/log/log.rb:29:in `call'","/usr/src/app/core/middleware/identifier/identifier.rb:12:in `call'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:32:in `block in call'","/usr/local/bundle/rub
Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,797 - ERROR: Json decoding error: y/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:61:in `block in trace'","/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:61:in `trace'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:32:in `call'","/usr/src/app/core/middleware/prometheus/prometheus_collector_http.rb:13:in `call'","/usr/local/bundle/ruby/2.6.0/gems/sentry-raven-2.9.0/lib/raven/integrations/rack.rb:51:in `call'","/usr/src/app/core/middleware/rpc/helpers/processes.rb:53:in `rpc_process_request'","/usr/src/app/core/middleware/rpc/helpers/processes.rb:8:in `rpc_process'","/usr/src/app/core/middleware/rpc/rpc.rb:31:in `block in call'","/usr/src/app/core/middleware/rpc/rpc.rb:30:in `map'","/usr/src/app/core/middleware/rpc/rpc.rb:30:in `call'","/usr/src/app/background/helpers/threadpool_send.rb:45:in `block in threadpool_send'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'"]}}}}]
Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,896 - ERROR: Json decoding error: [{"jsonrpc":"2.0","id":2,"error":{"code":-32006,"message":"Not Found","data":{"meta":{"type":"httpresponse","version":"2.0"},"message":"Id in url not found","data":{"wrong_parameter":"id","wrong_value":"7d768190-d86d-467d-9a6c-d8fea126ec56"},"code":9900147,"service":"data_collector","internal_code":"id_in_url_not_found","debug":{"file_line":"/usr/src/app/core/middleware/parsers/parser_path/helpers/checkers.rb:36:in `check_id'","backtrace":["/usr/src/app/core/middleware/parsers/parser_path/helpers/checkers.rb:36:in `check_id'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:46:in `block in check_url'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:10:in `each'","/usr/src/app/core/middleware/parsers/parser_path/helpers/check_url.rb:10:in `check_url'","/usr/src/app/core/middleware/parsers/parser_path/parser_path.rb:45:in `parse'","/usr/src/app/core/middleware/parsers/parser_path/parser_path.rb:13:in `call'","/usr/src/app/middleware/convert_old/convert_old.rb:17:in `call'","/usr/src/app/core/middleware/wallet/wallet.rb:20:in `call'","/usr/src/app/core/middleware/session/session.rb:14:in `call'","/usr/src/app/core/middleware/store/store.rb:12:in `call'","/usr/src/app/core/middleware/after_operation/after_operation.rb:8:in `call'","/usr/src/app/core/middleware/documentstore/documentstore.rb:15:in `call'","/usr/src/app/core/middleware/catchers/catch.rb:18:in `block in call'","/usr/src/app/core/middleware/catchers/catch.rb:17:in `catch'","/usr/src/app/core/middleware/catchers/catch.rb:17:in `call'","/usr/src/app/core/middleware/events/events.rb:12:in `call'","/usr/src/app/core/middleware/catchers/rescuer.rb:18:in `call'","/usr/src/app/core/middleware/identifier/trace.rb:17:in `call'","/usr/src/app/core/middleware/log/log.rb:29:in `call'","/usr/src/app/core/middleware/identifier/identifier.rb:12:in `call'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:32:in `block in call'","/usr/local/bundle/rub
Apr 01 09:58:04 PQPI-7d768190 rapid-prototype-runner[384]: 2020-04-01 09:58:04,920 - ERROR: Json decoding error: y/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:61:in `block in trace'","/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:61:in `trace'","/usr/local/bundle/ruby/2.6.0/gems/prometheus-client-2.0.0/lib/prometheus/middleware/collector.rb:32:in `call'","/usr/src/app/core/middleware/prometheus/prometheus_collector_http.rb:13:in `call'","/usr/local/bundle/ruby/2.6.0/gems/sentry-raven-2.9.0/lib/raven/integrations/rack.rb:51:in `call'","/usr/src/app/core/middleware/rpc/helpers/processes.rb:53:in `rpc_process_request'","/usr/src/app/core/middleware/rpc/helpers/processes.rb:8:in `rpc_process'","/usr/src/app/core/middleware/rpc/rpc.rb:31:in `block in call'","/usr/src/app/core/middleware/rpc/rpc.rb:30:in `map'","/usr/src/app/core/middleware/rpc/rpc.rb:30:in `call'","/usr/src/app/background/helpers/threadpool_send.rb:45:in `block in threadpool_send'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'","/usr/local/bundle/ruby/2.6.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'"]}}}}]`

**Comment by tacozMacleo** [comment]
This Issue is the same as "Failed to handle large bulk reply" #75 issue.
Some the message are to large to handle.
And since it is only a problem when we get debug info in the error message, it is not a high priority.
