### ISSUE TITLE
Support trace id for all out going messages.

### ISSUE THREAD

**Issue by AndreasBomholtz** [Wappsto/wappsto-python#16]
There need to be an option to enable trace for all messages.

**Comment by bubriks** [comment]
For SuccessResponse and ErrorResponse I do not know how to send the URL with trace id, as they follow a rigid structure and don't allow for more attributes.
SuccessResponse: {"jsonrpc": "2.0", "result": null, "id": 1}
ErrorResponse : {"jsonrpc": "2.0", "error": {"code": null, "message": null, "data": null}, "id": 1}
