### ISSUE TITLE
Send complete network in single POST message

### ISSUE THREAD

**Issue by AndreasBomholtz** [Wappsto/wappsto-python#20]
When the first POST message is send, it should be a complete network json, with all devices and values...

**Comment by bubriks** [comment]
b'{"jsonrpc": "2.0", "method": "PUT", "params": {"url": "/network/b03f246d-63ef-446d-be58-ef1d1e83b338", "data": {"meta": {"type": "network", "version": "2.0", "id": "b03f246d-63ef-446d-be58-ef1d1e83b338"}, "name": "test-network", "device": [{"meta": {"type": "device", "version": "2.0", "id": "a0e087c1-9678-491c-ac47-5b065dea3ac0"}, "name": "device-1", "product": "", "serial": "", "description": "", "protocol": "", "communication": "", "version": "", "manufacturer": "8989", "value": [{"meta": {"type": "value", "version": "2.0", "id": "7ce2afdd-3be3-4945-862e-c73a800eb209"}, "name": "temp", "permission": "rw", "type": "light", "number": {"min": 0, "max": 100, "step": 1, "unit": "%"}, "state": [{"meta": {"type": "state", "version": "2.0", "id": "a7b4f66b-2558-4559-9fcc-c60768083164", "contract": []}, "data": "8", "type": "Report", "timestamp": "2020-01-20T09:20:21.092Z"}, {"meta": {"type": "state", "version": "2.0", "id": "c9aca96b-ca89-4fce-9740-ca19207b64f2", "contract": []}, "data": "10", "type": "Control", "timestamp": "2020-01-20T09:20:21.092Z"}]}]}]}}, "id": 1}'
